version: '3'

services:
  sdnext-ipex:
    build:
      context: sdnext
      dockerfile: Dockerfile
    image: sdnext-ipex:latest
    container_name: sdnext-ipex
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri
    ports:
      - 7860:7860
    volumes:
      - sdnext-app-volume:/app
      - sdnext-mnt-volume:/mnt
      - sdnext-huggingface-volume:/root/.cache/huggingface
      - sdnext-python-volume:/usr/local/lib/python3.10

volumes:
  sdnext-app-volume: {}
  sdnext-mnt-volume: {}
  sdnext-python-volume: {}
  sdnext-huggingface-volume: {}
